networks:
    apigestionpresupuestal:
        driver: bridge

services:
  sqlserverdocker:
     container_name: mssql-db-test
     hostname: mssql-db-test
     image: mcr.microsoft.com/mssql/server:2022-latest
     ports:
        - "8002:1433"
     environment:
        ACCEPT_EULA: 'Y'
        MSSQL_SA_PASSWORD: 'Admin@123'
        MSSQL_DATA_DIR: /var/opt/mssql/data
        MSSQL_PID: 'Developer' 
        MSSQL_TCP_PORT: 1433 
     volumes:
        - ./db/data:/var/opt/mssql/data
        - ./db/log:/var/opt/mssql/log
        - ./db/secrets:/var/opt/mssql/secrets
     networks:
        - apigestionpresupuestal
  apipresupuestal:        
    container_name: api-app-test
    image: drakonc/apipresupuestal:latest
    ports:
        - "8001:80"
    depends_on:
       - sqlserverdocker
    environment:
        DB_CONNECTION_STRING: "RGF0YSBTb3VyY2U9c3Fsc2VydmVyZG9ja2VyO0luaXRpYWwgQ2F0YWxvZz1kYkF6dXJlOyBVc2VyIElEPXNhO1Bhc3N3b3JkPUFkbWluQDEyMzsgVHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVl"
    networks:
        - apigestionpresupuestal